config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :object_names
  resources :orders, only: [:index, :show, :create, :destroy]
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'
  
  root 'static_pages#about'
  
  get '/products/:id', to: 'products#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/object_name.rb
class ObjectName < ApplicationRecord
end

app/models/order.rb
class Product < ApplicationRecord
   belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/object_names_controller.rb
class ObjectNamesController < ApplicationController
  before_action :set_object_name, only: [:show, :edit, :update, :destroy]

  # GET /object_names
  # GET /object_names.json
  def index
    @object_names = ObjectName.all
  end

  # GET /object_names/1
  # GET /object_names/1.json
  def show
  end

  # GET /object_names/new
  def new
    @object_name = ObjectName.new
  end

  # GET /object_names/1/edit
  def edit
  end

  # POST /object_names
  # POST /object_names.json
  def create
    @object_name = ObjectName.new(object_name_params)

    respond_to do |format|
      if @object_name.save
        format.html { redirect_to @object_name, notice: 'Object name was successfully created.' }
        format.json { render :show, status: :created, location: @object_name }
      else
        format.html { render :new }
        format.json { render json: @object_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /object_names/1
  # PATCH/PUT /object_names/1.json
  def update
    respond_to do |format|
      if @object_name.update(object_name_params)
        format.html { redirect_to @object_name, notice: 'Object name was successfully updated.' }
        format.json { render :show, status: :ok, location: @object_name }
      else
        format.html { render :edit }
        format.json { render json: @object_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /object_names/1
  # DELETE /object_names/1.json
  def destroy
    @object_name.destroy
    respond_to do |format|
      format.html { redirect_to object_names_url, notice: 'Object name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_object_name
      @object_name = ObjectName.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def object_name_params
      params.fetch(:object_name, {})
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    # @products = Product.all es iyo
    @products = Product.limit(3)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :colour)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @products = Product.all    
    @featured_product = Product.first
  end
  
  #def index
     #@products = Product.limit(3)
  #end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/object_names_helper.rb
module ObjectNamesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsapp</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag("application", :media => "all", "data-turbolinks-track" => true) %>
    
    <%= javascript_include_tag("application") %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>
  <body>
<div id="navbar">
	<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
		<div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">MariamWithLove</a>
        </div>
        <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
              
        <li class="active">
		<a href="#" class="hidden-xs">Home</a>
 		<a href="#" class="visible-xs" data-toggle="collapse" data-target=".navbar-collapse">Home</a>
		</li>
              
        <li>
		<a href="#products" class="hidden-xs">About</a>
		<a href="#products" class="visible-xs" data-toggle="collapse" data-target=".navbar-collapse">About</a>
		</li>
              
		<li>
		<a href="#overview" class="hidden-xs">Products</a>
		<a href="#overview" class="visible-xs" data-toggle="collapse" data-target=".navbar-collapse">Products</a>
		</li>
          
        <li>
		<a href="#overview" class="hidden-xs">Contact</a>
		<a href="#overview" class="visible-xs" data-toggle="collapse" data-target=".navbar-collapse">Contact</a>
		</li>
          
        </ul>
        </div><!--/.nav-collapse -->
    </div>
	</nav>
</div>
    
  </body>
   <%= yield %>
  <footer>
  &copy; 2016 MariamWithLove Georgia
  </footer>
  
</html>

app/views/object_names/_form.html.erb
<%= form_for(object_name) do |f| %>
  <% if object_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(object_name.errors.count, "error") %> prohibited this object_name from being saved:</h2>

      <ul>
      <% object_name.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/object_names/edit.html.erb
<h1>Editing Object Name</h1>

<%= render 'form', object_name: @object_name %>

<%= link_to 'Show', @object_name %> |
<%= link_to 'Back', object_names_path %>

app/views/object_names/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Object Names</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @object_names.each do |object_name| %>
      <tr>
        <td><%= link_to 'Show', object_name %></td>
        <td><%= link_to 'Edit', edit_object_name_path(object_name) %></td>
        <td><%= link_to 'Destroy', object_name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Object Name', new_object_name_path %>

app/views/object_names/new.html.erb
<h1>New Object Name</h1>

<%= render 'form', object_name: @object_name %>

<%= link_to 'Back', object_names_path %>

app/views/object_names/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_object_name_path(@object_name) %> |
<%= link_to 'Back', object_names_path %>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
  <%= f.label :colour %><br>
  <%= f.text_field :colour %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container-fluid">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-sm-2 col-md-4">
        <%= image_tag(product.image_url, class: "img-responsive") %>
        <h1><%= product.name %></h1>
        <p><%= product.description %></p>
        <strong>$ 42</strong>
      </div><!-- /col -->
    <% end %>
  </div>
</div>


<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Color</th>
      <th>Colour</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.image_url %></td>
        <td><%= product.colour %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @product.colour %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/static_pages/about.html.erb
<div class="message">
  <h1>CHANGE YOUR LIFE TODAY.<br>
  <span class="small">No bullshit, just what you need to get in shape mentally and physically.</span></h1>
</div>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>
<p>MariamWithLove@info.com</p>

app/views/static_pages/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
     <% @products.each do |product| %>
    <div class="item<%= " active" if product == @products.first %>">
      <%= image_tag(product.image_url) %>
      <div class="carousel-caption">
            <%= product.name %>
      </div>
    </div>
    <div class="item">
      <%= image_tag(product.image_url) %>
        <div class="carousel-caption">
            <%= product.name %>
        </div>
      </div>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="box1">
  <h2 class="text1">I am not a personal trainer.<br>I am not IFBB pro.</h2>
</div>
<div class="box2">
  <h2 class="text2">I inspire women all over the world to accept and better themselves in a natural and holistic way.<br>Everything I do, I give 100% hardcore effort.<br>I build dream bodies.
  </h2>
</div>